"""empty message

Revision ID: 077a40172534
Revises: 0a426a79535e
Create Date: 2021-11-09 18:16:35.407558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a40172534'
down_revision = '0a426a79535e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('checkins', sa.Column('updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'updated_at')
    op.drop_column('checkins', 'created_at')
    # ### end Alembic commands ###
