"""empty message

Revision ID: 0a426a79535e
Revises: e2a4ee6e5084
Create Date: 2021-11-09 12:46:23.682322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a426a79535e'
down_revision = 'e2a4ee6e5084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checkins_user_id_fkey', 'checkins', type_='foreignkey')
    op.create_foreign_key(None, 'checkins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.create_foreign_key('checkins_user_id_fkey', 'checkins', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
