"""empty message

Revision ID: 1892a95b590f
Revises: 3b791144a824
Create Date: 2021-11-11 14:58:47.101381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1892a95b590f'
down_revision = '3b791144a824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('checkins', 'location')
    op.add_column('distilleries', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('distilleries_email_key', 'distilleries', type_='unique')
    op.create_foreign_key(None, 'distilleries', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('distilleries', 'email')
    op.drop_column('distilleries', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distilleries', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('distilleries', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'distilleries', type_='foreignkey')
    op.create_unique_constraint('distilleries_email_key', 'distilleries', ['email'])
    op.drop_column('distilleries', 'owner_id')
    op.add_column('checkins', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('checkins', 'image')
    # ### end Alembic commands ###
