"""updating cascading

Revision ID: 37b7a25d3798
Revises: 5599af5d95c8
Create Date: 2021-11-09 09:46:55.126575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b7a25d3798'
down_revision = '5599af5d95c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'drink_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checkins', 'distillery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'distillery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('checkins', 'drink_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
