"""empty message

Revision ID: 3b791144a824
Revises: 00418a55b30a
Create Date: 2021-11-11 12:36:05.850080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b791144a824'
down_revision = '00418a55b30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'location')
    # ### end Alembic commands ###
