"""empty message

Revision ID: 5599af5d95c8
Revises: 3ba2f279fc3c
Create Date: 2021-11-08 09:59:42.223639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5599af5d95c8'
down_revision = '3ba2f279fc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'distillery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'distillery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
