"""empty message

Revision ID: 70537004ce36
Revises: de65b08125c0
Create Date: 2021-11-09 19:31:14.816006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70537004ce36'
down_revision = 'de65b08125c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('checkins', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'updated_at')
    op.drop_column('checkins', 'created_at')
    # ### end Alembic commands ###
