"""empty message

Revision ID: 74dec1af5458
Revises: 8f77de7ed454
Create Date: 2021-11-11 17:45:38.575103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74dec1af5458'
down_revision = '8f77de7ed454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('drink_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'drink_name')
    # ### end Alembic commands ###
