"""empty message

Revision ID: b0867d366934
Revises: 8c35da0d39e6
Create Date: 2021-11-11 13:32:41.363023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0867d366934'
down_revision = '8c35da0d39e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('image', sa.String(), nullable=True))
    op.add_column('distilleries', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('distilleries_email_key', 'distilleries', type_='unique')
    op.create_foreign_key(None, 'distilleries', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('distilleries', 'hashed_password')
    op.drop_column('distilleries', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distilleries', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('distilleries', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'distilleries', type_='foreignkey')
    op.create_unique_constraint('distilleries_email_key', 'distilleries', ['email'])
    op.drop_column('distilleries', 'owner_id')
    op.drop_column('checkins', 'image')
    # ### end Alembic commands ###
