"""empty message

Revision ID: de65b08125c0
Revises: 077a40172534
Create Date: 2021-11-09 19:27:26.529717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de65b08125c0'
down_revision = '077a40172534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'drink_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('checkins', 'distillery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('checkins', 'updated_at')
    op.drop_column('checkins', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('checkins', sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('checkins', 'distillery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checkins', 'drink_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
