"""empty message

Revision ID: e2a4ee6e5084
Revises: ecb10cc2cc77
Create Date: 2021-11-09 10:12:11.394307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a4ee6e5084'
down_revision = 'ecb10cc2cc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checkins_distillery_id_fkey', 'checkins', type_='foreignkey')
    op.drop_constraint('checkins_drink_id_fkey', 'checkins', type_='foreignkey')
    op.create_foreign_key(None, 'checkins', 'distilleries', ['distillery_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'checkins', 'drinks', ['drink_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.create_foreign_key('checkins_drink_id_fkey', 'checkins', 'drinks', ['drink_id'], ['id'])
    op.create_foreign_key('checkins_distillery_id_fkey', 'checkins', 'distilleries', ['distillery_id'], ['id'])
    # ### end Alembic commands ###
