"""empty message

Revision ID: ecb10cc2cc77
Revises: 37b7a25d3798
Create Date: 2021-11-09 09:57:49.708936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb10cc2cc77'
down_revision = '37b7a25d3798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drinks_distillery_id_fkey', 'drinks', type_='foreignkey')
    op.create_foreign_key(None, 'drinks', 'distilleries', ['distillery_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drinks', type_='foreignkey')
    op.create_foreign_key('drinks_distillery_id_fkey', 'drinks', 'distilleries', ['distillery_id'], ['id'])
    # ### end Alembic commands ###
